# Generated by Django 4.1.5 on 2023-02-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
    ]
