# Generated by Django 4.1.5 on 2023-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='mailed',
            field=models.BooleanField(default=False),
        ),
    ]
