# Generated by Django 4.1.5 on 2023-05-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_globalsettings_invoice_global_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='discount_amount',
            new_name='discount_value',
        ),
    ]
