# Generated by Django 4.1.5 on 2023-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_globalsettings_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
