# Generated by Django 4.1.5 on 2023-02-15 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_documentpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpdf',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
