# Generated by Django 4.1.5 on 2023-02-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_documentpdf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpdf',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
