# Generated by Django 4.1.5 on 2023-05-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_tax_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='sequence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
