# Generated by Django 4.1.5 on 2023-02-17 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_documentpdf_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpdf',
            old_name='document_pdf',
            new_name='file_pdf',
        ),
        migrations.RemoveField(
            model_name='documentpdf',
            name='name',
        ),
        migrations.AddField(
            model_name='documentpdf',
            name='file_name',
            field=models.CharField(default=datetime.datetime(2023, 2, 17, 22, 39, 3, 587601, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
