# Generated by Django 4.1.5 on 2023-05-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_globalsettings_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='last_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
