# Generated by Django 4.1.5 on 2023-05-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='last_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
