# Generated by Django 4.1.5 on 2023-02-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_client_address_client_city_client_company_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
