# Generated by Django 4.1.5 on 2023-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_globalsettings_last_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='lead_zeros_format',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
