# Generated by Django 4.1.5 on 2023-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_globalsettings_lead_zeros_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unique_code_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
