# Generated by Django 4.1.5 on 2023-06-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alias',
            field=models.CharField(blank=True, default='Default', max_length=100, null=True),
        ),
    ]
