# Generated by Django 4.1.5 on 2023-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_address_options_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinfo',
            name='sent_timestamp',
            field=models.DateTimeField(),
        ),
    ]
