# Generated by Django 4.1.5 on 2023-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_rename_tax_base_invoicesetting_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax_base',
            new_name='total_base',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='tax_quantity',
            new_name='total_discount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
