# Generated by Django 4.1.5 on 2023-02-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoice_invoice_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicesetting',
            old_name='tax_base',
            new_name='tax',
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
