# Generated by Django 4.1.5 on 2023-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_rename_tax_base_invoicesetting_tax_invoice_tax_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_products',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
