# Generated by Django 4.1.5 on 2023-06-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_alter_mailinfo_sent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinfo',
            name='sent_timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
