# Generated by Django 4.1.5 on 2023-02-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_client_email_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpdf',
            name='file_name',
        ),
    ]
