# Generated by Django 4.1.5 on 2023-06-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_alter_mailinfo_sent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinfo',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
