# Generated by Django 4.1.5 on 2023-02-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_remove_documentpdf_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpdf',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
    ]
