# Generated by Django 4.1.5 on 2023-06-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_alter_mailinfo_sent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='customer_information_file_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
