# Generated by Django 4.1.5 on 2023-02-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_rename_company_id_number_client_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='additional_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_contact', to='invoices.contact'),
        ),
    ]
