# Generated by Django 4.1.5 on 2023-03-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_alter_client_additional_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpdf',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.client'),
        ),
    ]
